trainers = [
    "Ash Ketchum", "Misty Waterflower", "Brock Rock", "Serena Moon", "Gary Oak",
    "May Maple", "Dawn Berlitz", "Iris", "Cilan Chili", "Lillie Luminous",
    "Erika Grassfield", "Clemont Lumiose", "Misty Moss", "Max",
    "Jessie Rocket", "James Rocket", "Cynthia Champion", "Rian",
    "Bruno", "Agatha", "Lorelei", "Koga", "Sabrina",
    "Blaine", "Lt. Surge Volt", "Janine", "Bugsy", "Falkner",
    "Morty Ecruteak", "Whitney", "Morty Ecruteak", "Pryce", "Clair",
    "Wallace", "Roxanne", "Brawly", "Flannery", "Norman",
    "Winona", "Tate", "Liza", "Juan Sootopolis", "Liza Mossdeep",
    "Tucker Battle Frontier", "Lucy Battle Frontier", "Anabel Battle Frontier", "Brandon Pyramid King",
    "Noland Battle Factory", "Greta Battle Arena", "Spenser Battle Palace", "Palmer Battle Tower",
    "Palmer Sinnoh", "Cheryl Eterna Forest", "Marley Victory Road", "Riley Iron Island", "Buck Stark Mountain",
    "Rowan Professor", "Sycamore Professor", "Kukui Professor", "Willow Professor", "Elm Professor", "Birch Professor",
    "Juniper Professor", "Elm Johto", "Juniper Unova", "Rowan Sinnoh", "Birch Hoenn", "Kricketune Player",
    "Entei Explorer", "Suicune Seeker", "Phoebe Elite Four", "Bertha Elite Four", "Flint Elite Four", "Grimsley Elite Four",
    "Shauntal Elite Four", "Marshal Elite Four", "Caitlin Elite Four", "Malva Elite Four", "Siebold Elite Four",
    "Wikstrom Elite Four", "Drasna Elite Four", "Piers Spikemuth", "Raihan Hammerlocke", "Bea Stow-on-Side", "Allister Stow-on-Side",
    "Red Champion", "Lance Dragon Master", "Blue Oak"
]

pokemon_list = [
    "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon",
    "Charizard", "Squirtle", "Wartortle", "Blastoise", "Caterpie",
    "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill",
    "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate",
    "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu",
    "Raichu", "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina",
    "Nidoqueen", "Nidoran♂", "Nidorino", "Nidoking", "Clefairy",
    "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff",
    "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume",
    "Paras", "Parasect", "Venonat", "Venomoth", "Digglet",
    "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck",
    "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag",
    "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam",
    "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell",
    "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler",
    "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro",
    "Magnemite", "Magneton", "Farfetch'd", "Doduo", "Dodrio",
    "Seel", "Dewgong", "Grimer", "Muk", "Shellder",
    "Cloyster", "Gastly", "Haunter", "Gengar", "Onix",
    "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb",
    "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak",
    "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing",
    "Rhyhorn", "Rhydon", "Chansey", "Tangela", "Kangaskhan",
    "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu",
    "Starmie", "Mr. Mime", "Scyther", "Jynx", "Electabuzz",
    "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados",
    "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon",
    "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto",
    "Kabutops", "Aerodactyl", "Snorlax", "Dratini", "Dragonair",
    "Dragonite"]

legendary_pokemon = ["Articuno", "Zapdos", "Moltres", "Mewtwo", "Mew"]
lance_pokemon = ["Gyarados", "Dragonair", "Aerodactyl", "Dragonite"]
red_pokemon = ["Pidgeot", "Alakazam", "Rhydon", "Arcanine","Pikachu","Exeggutor","Charizard", "Blastoise", "Venusaur"]
ash_pokemon = ["Pikachu","Charizard","Bulbasaur","Squirtle","Kingler","Muk","Tauros"]
misty_pokemon = ["Starmie","Psyduck","Seadra","Goldeen","Poliwhirl"]
brock_pokemon = ["Geodude","Onix","Zubat"]

pokedex = {
    "bulbasaur": {"favorite_skill": "solar beam"},
    "ivysaur": {"favorite_skill": "vine whip"},
    "venusaur": {"favorite_skill": "frenzy plant"},
    "charmander": {"favorite_skill": "flamethrower"},
    "charmeleon": {"favorite_skill": "dragon rage"},
    "charizard": {"favorite_skill": "fire blast"},
    "squirtle": {"favorite_skill": "hydro pump"},
    "wartortle": {"favorite_skill": "bubble beam"},
    "blastoise": {"favorite_skill": "surf"},
    "caterpie": {"favorite_skill": "tackle"},
    "metapod": {"favorite_skill": "harden"},
    "butterfree": {"favorite_skill": "gust"},
    "weedle": {"favorite_skill": "poison sting"},
    "kakuna": {"favorite_skill": "harden"},
    "beedrill": {"favorite_skill": "twin needle"},
    "pidgey": {"favorite_skill": "gust"},
    "pidgeotto": {"favorite_skill": "wing attack"},
    "pidgeot": {"favorite_skill": "sky attack"},
    "rattata": {"favorite_skill": "tackle"},
    "raticate": {"favorite_skill": "hyper fang"},
    "spearow": {"favorite_skill": "peck"},
    "fearow": {"favorite_skill": "drill peck"},
    "ekans": {"favorite_skill": "poison jab"},
    "arbok": {"favorite_skill": "gunk shot"},
    "pikachu": {"favorite_skill": "thunderbolt"},
    "raichu": {"favorite_skill": "thunder"},
    "sandshrew": {"favorite_skill": "dig"},
    "sandslash": {"favorite_skill": "earthquake"},
    "nidoran♀": {"favorite_skill": "poison sting"},
    "nidorina": {"favorite_skill": "double kick"},
    "nidoran♂": {"favorite_skill": "peck"},
    "nidorino": {"favorite_skill": "horn attack"},
    "nidoking": {"favorite_skill": "earthquake"},
    "nidoqueen": {"favorite_skill": "earthquake"},
    "clefairy": {"favorite_skill": "metronome"},
    "clefable": {"favorite_skill": "moonblast"},
    "vulpix": {"favorite_skill": "ember"},
    "ninetales": {"favorite_skill": "flamethrower"},
    "jigglypuff": {"favorite_skill": "sing"},
    "wigglytuff": {"favorite_skill": "dazzling gleam"},
    "zubat": {"favorite_skill": "supersonic"},
    "golbat": {"favorite_skill": "air slash"},
    "oddish": {"favorite_skill": "absorb"},
    "gloom": {"favorite_skill": "mega drain"},
    "vileplume": {"favorite_skill": "petal dance"},
    "paras": {"favorite_skill": "scratch"},
    "parasect": {"favorite_skill": "x-scissor"},
    "venonat": {"favorite_skill": "tackle"},
    "venomoth": {"favorite_skill": "confusion"},
    "digglet": {"favorite_skill": "scratch"},
    "dugtrio": {"favorite_skill": "earthquake"},
    "meowth": {"favorite_skill": "pay day"},
    "persian": {"favorite_skill": "slash"},
    "psyduck": {"favorite_skill": "water gun"},
    "golduck": {"favorite_skill": "hydro pump"},
    "mankey": {"favorite_skill": "karate chop"},
    "primeape": {"favorite_skill": "cross chop"},
    "growlithe": {"favorite_skill": "ember"},
    "arcanine": {"favorite_skill": "flamethrower"},
    "poliwag": {"favorite_skill": "bubble"},
    "poliwhirl": {"favorite_skill": "water gun"},
    "poliwrath": {"favorite_skill": "hydro pump"},
    "abra": {"favorite_skill": "teleport"},
    "kadabra": {"favorite_skill": "psybeam"},
    "alakazam": {"favorite_skill": "psychic"},
    "machop": {"favorite_skill": "karate chop"},
    "machoke": {"favorite_skill": "low kick"},
    "machamp": {"favorite_skill": "dynamic punch"},
    "bellsprout": {"favorite_skill": "vine whip"},
    "weepinbell": {"favorite_skill": "acid"},
    "victreebel": {"favorite_skill": "leaf blade"},
    "tentacool": {"favorite_skill": "poison sting"},
    "tentacruel": {"favorite_skill": "hydro pump"},
    "geodude": {"favorite_skill": "rock throw"},
    "graveler": {"favorite_skill": "rock slide"},
    "golem": {"favorite_skill": "earthquake"},
    "ponyta": {"favorite_skill": "ember"},
    "rapidash": {"favorite_skill": "fire blast"},
    "slowpoke": {"favorite_skill": "water gun"},
    "slowbro": {"favorite_skill": "psychic"},
    "magnemite": {"favorite_skill": "thunder shock"},
    "magneton": {"favorite_skill": "thunderbolt"},
    "farfetch'd": {"favorite_skill": "peck"},
    "doduo": {"favorite_skill": "peck"},
    "dodrio": {"favorite_skill": "tri attack"},
    "seel": {"favorite_skill": "aqua jet"},
    "dewgong": {"favorite_skill": "aurora beam"},
    "grimer": {"favorite_skill": "mud slap"},
    "muk": {"favorite_skill": "gunk shot"},
    "shellder": {"favorite_skill": "tackle"},
    "cloyster": {"favorite_skill": "icicle spear"},
    "gastly": {"favorite_skill": "lick"},
    "haunter": {"favorite_skill": "shadow ball"},
    "gengar": {"favorite_skill": "sludge bomb"},
    "onix": {"favorite_skill": "rock throw"},
    "drowzee": {"favorite_skill": "confusion"},
    "hypno": {"favorite_skill": "psyshock"},
    "krabby": {"favorite_skill": "bubble"},
    "kingler": {"favorite_skill": "crabhammer"},
    "voltorb": {"favorite_skill": "spark"},
    "electrode": {"favorite_skill": "thunderbolt"},
    "exeggcute": {"favorite_skill": "bullet seed"},
    "exeggutor": {"favorite_skill": "solar beam"},
    "cubone": {"favorite_skill": "bone club"},
    "marowak": {"favorite_skill": "shadow bone"},
    "hitmonlee": {"favorite_skill": "high jump kick"},
    "hitmonchan": {"favorite_skill": "mach punch"},
    "lickitung": {"favorite_skill": "lick"},
    "koffing": {"favorite_skill": "poison gas"},
    "weezing": {"favorite_skill": "sludge bomb"},
    "rhyhorn": {"favorite_skill": "stomp"},
    "rhydon": {"favorite_skill": "megahorn"},
    "chansey": {"favorite_skill": "pound"},
    "tangela": {"favorite_skill": "vine whip"},
    "kangaskhan": {"favorite_skill": "comet punch"},
    "horsea": {"favorite_skill": "bubble"},
    "seadra": {"favorite_skill": "water gun"},
    "goldeen": {"favorite_skill": "peck"},
    "seaking": {"favorite_skill": "horn attack"},
    "staryu": {"favorite_skill": "water gun"},
    "starmie": {"favorite_skill": "psychic"},
    "mr. mime": {"favorite_skill": "confusion"},
    "scyther": {"favorite_skill": "wing attack"},
    "jynx": {"favorite_skill": "powder snow"},
    "electabuzz": {"favorite_skill": "thunder punch"},
    "magmar": {"favorite_skill": "ember"},
    "pinsir": {"favorite_skill": "vice grip"},
    "tauros": {"favorite_skill": "horn attack"},
    "magikarp": {"favorite_skill": "splash"},
    "gyarados": {"favorite_skill": "hydro pump"},
    "lapras": {"favorite_skill": "ice beam"},
    "ditto": {"favorite_skill": "transform"},
    "eevee": {"favorite_skill": "tackle"},
    "vaporeon": {"favorite_skill": "aqua tail"},
    "jolteon": {"favorite_skill": "thunder shock"},
    "flareon": {"favorite_skill": "ember"},
    "porygon": {"favorite_skill": "tackle"},
    "omanyte": {"favorite_skill": "water gun"},
    "omastar": {"favorite_skill": "rock throw"},
    "kabuto": {"favorite_skill": "mud shot"},
    "kabutops": {"favorite_skill": "fury cutter"},
    "aerodactyl": {"favorite_skill": "steel wing"},
    "snorlax": {"favorite_skill": "hyper beam"},
    "articuno": {"favorite_skill": "ice beam"},
    "zapdos": {"favorite_skill": "thunder shock"},
    "moltres": {"favorite_skill": "ember"},
    "dratini": {"favorite_skill": "dragon breath"},
    "dragonair": {"favorite_skill": "aqua tail"},
    "dragonite": {"favorite_skill": "dragon claw"},
    "mewtwo": {"favorite_skill": "psychic"},
    "mew": {"favorite_skill": "psychic"}
}

pokemon_hp = {
    "bulbasaur": 318,
    "ivysaur": 405,
    "venusaur": 525,
    "charmander": 309,
    "charmeleon": 405,
    "charizard": 534,
    "squirtle": 314,
    "wartortle": 405,
    "blastoise": 530,
    "caterpie": 195,
    "metapod": 205,
    "butterfree": 395,
    "weedle": 195,
    "kakuna": 205,
    "beedrill": 395,
    "pidgey": 251,
    "pidgeotto": 349,
    "pidgeot": 479,
    "rattata": 253,
    "raticate": 413,
    "spearow": 262,
    "fearow": 442,
    "ekans": 288,
    "arbok": 448,
    "pikachu": 320,
    "raichu": 485,
    "sandshrew": 300,
    "sandslash": 450,
    "nidoran♀": 275,
    "nidorina": 365,
    "nidoran♂": 273,
    "nidorino": 365,
    "nidoking": 505,
    "nidoqueen": 505,
    "clefairy": 323,
    "clefable": 483,
    "vulpix": 299,
    "ninetales": 505,
    "jigglypuff": 270,
    "wigglytuff": 435,
    "zubat": 245,
    "golbat": 455,
    "oddish": 320,
    "gloom": 395,
    "vileplume": 490,
    "paras": 285,
    "parasect": 405,
    "venonat": 305,
    "venomoth": 450,
    "digglet": 265,
    "dugtrio": 405,
    "meowth": 290,
    "persian": 440,
    "psyduck": 320,
    "golduck": 500,
    "mankey": 305,
    "primeape": 455,
    "growlithe": 350,
    "arcanine": 555,
    "poliwag": 300,
    "poliwhirl": 385,
    "poliwrath": 510,
    "abra": 310,
    "kadabra": 400,
    "alakazam": 500,
    "machop": 305,
    "machoke": 405,
    "machamp": 505,
    "bellsprout": 300,
    "weepinbell": 390,
    "victreebel": 490,
    "tentacool": 335,
    "tentacruel": 515,
    "geodude": 300,
    "graveler": 390,
    "golem": 495,
    "ponyta": 410,
    "rapidash": 500,
    "slowpoke": 315,
    "slowbro": 490,
    "magnemite": 325,
    "magneton": 465,
    "farfetch'd": 352,
    "doduo": 310,
    "dodrio": 470,
    "seel": 325,
    "dewgong": 475,
    "grimer": 325,
    "muk": 500,
    "shellder": 305,
    "cloyster": 525,
    "gastly": 310,
    "haunter": 405,
    "gengar": 500,
    "onix": 385,
    "drowzee": 328,
    "hypno": 483,
    "krabby": 325,
    "kingler": 475,
    "voltorb": 330,
    "electrode": 480,
    "exeggcute": 325,
    "exeggutor": 520,
    "cubone": 320,
    "marowak": 425,
    "hitmonlee": 455,
    "hitmonchan": 455,
    "lickitung": 385,
    "koffing": 340,
    "weezing": 490,
    "rhyhorn": 345,
    "rhydon": 485,
    "chansey": 450,
    "tangela": 435,
    "kangaskhan": 490,
    "horsea": 295,
    "seadra": 440,
    "goldeen": 320,
    "seaking": 450,
    "staryu": 340,
    "starmie": 520,
    "mr. mime": 460,
    "scyther": 500,
    "jynx": 455,
    "electabuzz": 490,
    "magmar": 495,
    "pinsir": 500,
    "tauros": 490,
    "magikarp": 200,
    "gyarados": 540,
    "lapras": 535,
    "ditto": 288,
    "eevee": 325,
    "vaporeon": 525,
    "jolteon": 525,
    "flareon": 525,
    "porygon": 395,
    "omanyte": 355,
    "omastar": 495,
    "kabuto": 355,
    "kabutops": 495,
    "aerodactyl": 515,
    "snorlax": 540,
    "articuno": 580,
    "zapdos": 580,
    "moltres": 580,
    "dratini": 300,
    "dragonair": 420,
    "dragonite": 600,
    "mewtwo": 680,
    "mew": 600
}